name: deploy react to github pages
on:
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/*'
      - README.md
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: install node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies 
        run: npm ci
      - name: run test cases
        run: npm run test
